# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8613e033ed51506edfe6ed568bf6a6e710d182f7cb183b11915d8b648c081425a5eacbbf19ba6cdbbd11dd52809dd9295a4b3c0e1f28b6e0186b288d7a5d0a4

test:
  secret_key_base: cdb25c283d2c844e273649321fcdca0b3a0cef24de21523c7ddf1aca22c51746203016b3485c910d99e8bcfdf13912216651d3bb0ee366c9201a51cddb7273d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
